[package]
name = "birdwatcher-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.14.0"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
toml = "0.8.20"
