[package]
name = "birdwatcher-rs"
version = "0.1.0"
edition = "2021"
description = "Run periodic healthcheck on a service to automatically stop or start [BIRD](https://bird.network.cz/) advertisements."
authors = ["Julien Gautier"]
license = "MIT OR Apache-2.0"


[dependencies]
anyhow = { version = "1.0.97", features = ["backtrace"] }
clap = { version = "4.5.33", features = ["derive"] }
fs-err = "3.1.0"
itertools = "0.14.0"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
toml = "0.8.20"

[dev-dependencies]
pretty_assertions = "1.4.1"
indoc = "2"
