[package]
name = "birdwatcher-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
async-scoped = {version = "0.9.0", features = ["use-tokio"]}
itertools = "0.14.0"
tokio = { version = "1", features = ["full"] }
